/* =================================================================
   ALL SITE CONTENT LIVES HERE.
   To add a project: add an object to `projects`, drop a markdown
   file in content/projects/<slug>.md, optionally add a thumbnail
   to assets/thumbs/. That's it.
   To add an article: add an object to `writing`.
   ================================================================= */

const SITE = {
  name: "Pranav Kumaar",
  role: "Software Engineer · AI/ML Systems",
  intro:
    "I build LLM orchestration, retrieval systems, and production ML infrastructure. Starting my MS in Computer Science at UMass Amherst, Fall 2026. Based in Bangalore, India.",
  // Recruiter-facing availability. Shown as a status pill in the hero and baked
  // into the social card + JSON-LD. `open: true` renders the pill.
  availability: {
    open: true,
    label: "Open to Summer 2027 internships & full-time 2028",
    detail: "SWE / ML roles · relocating to the US (UMass Amherst, Fall 2026)",
  },
  location: "Bangalore, India → Amherst, MA (Fall 2026)",
  email: "pranavkumaarofficial@gmail.com",
  github: "https://github.com/pranavkumaarofficial",
  linkedin: "https://linkedin.com/in/pranavkumaarofficial",
  resume: "assets/resume.pdf", // drop your resume PDF at this path
};

/* Ventures + Projects both get full case-study pages (generated by
   tools/build.mjs). `type` routes them into the right homepage section:
     type: "venture"  -> Ventures section (founded / pitched / took to market)
     type: "project"  -> Projects section (deep engineering & research)
   Optional `badge` overrides the auto "Code / Case study" card label. */
const PROJECTS = [
  {
    slug: "channel-ai",
    type: "venture",
    title: "Channel AI",
    subtitle: "Multi-agent conversational analytics · 12 pilot deployments",
    summary:
      "Non-technical teams query their business data over WhatsApp in plain language. Cut reporting turnaround from ~2 days to under 30 minutes across 12 pilots.",
    seoDescription:
      "Channel AI case study: multi-agent conversational analytics over a Spark + Apache Iceberg lakehouse. Federated querying across Excel, RDBMS, and BigQuery; transient CTAS materialization; grain and value-linking failure classes. 12 pilot deployments.",
    tags: ["LangGraph", "Apache Iceberg", "Spark", "Federated SQL"],
    thumb: "assets/thumbs/channel-ai.svg",
    repo: "https://github.com/pranavkumaarofficial/channel-ai-enterprise",
    featured: true,
  },
  {
    slug: "sustify",
    type: "venture",
    title: "Sustify",
    subtitle: "AI-driven sustainability marketplace",
    summary:
      "Founded a marketplace using transformer embeddings for automated requirement matching and vendor recommendations.",
    tags: ["BERT", "OpenAI Embeddings", "Python"],
    thumb: "assets/thumbs/sustify.svg",
    repo: "",
    featured: true,
  },
  {
    slug: "kg-rag-research",
    type: "project",
    badge: "Research",
    title: "When Graph Structure Hurts",
    subtitle: "Lightweight path ranking for dense KG-RAG · ICMLC 2026",
    summary:
      "A simple MLP scorer hits 93.9% AUC on dense citation graphs, beating GCN and GAT with 13× fewer parameters.",
    tags: ["Knowledge Graphs", "RAG", "PyTorch", "GNN"],
    thumb: "assets/thumbs/kg-rag.svg",
    repo: "",
    featured: true,
  },
  {
    slug: "onesku",
    type: "project",
    title: "OneSKU",
    subtitle: "Hybrid BM25 + embedding retrieval",
    summary:
      "Hybrid retrieval with a custom harmonization pipeline for heterogeneous vendor catalogs. Sub-15s queries across multi-million SKU inventories.",
    tags: ["PyTorch", "BM25", "BERT", "Embeddings"],
    thumb: "assets/thumbs/onesku.svg",
    repo: "",
    featured: true,
  },
  {
    slug: "est-service",
    type: "project",
    title: "EST Certificate Management",
    subtitle: "Production PKI infrastructure",
    summary:
      "Led end-to-end development of an EST service for automated certificate issuance and rotation across internal microservices.",
    tags: ["Python", "PKI / EST", "Docker", "Kubernetes"],
    thumb: "assets/thumbs/est.svg",
    repo: "",
    featured: true,
  },
];

/* Open Source: lightweight. NO detail page: each card links straight to GitHub.
   The section stays hidden until this array has entries (like Writing).
   Add one object per repo:
     { name: "repo-name", desc: "One line on what it does.",
       lang: "Python", tags: ["CLI"], repo: "https://github.com/you/repo" }
   `lang` shows on the right; `tags` are optional. */
const OSS_INTRO =
  "Small tools I've built in the open, plus repos I contribute to. Lighter than the work above. Browse if curious.";

const OSS = [
  {
    name: "nlcli-wizard",
    desc: "Natural-language control for Python CLI tools, powered by locally fine-tuned small language models, quantized for CPU-only inference with no API calls.",
    lang: "Python",
    tags: ["SLM", "Fine-tuning", "Quantization"],
    repo: "https://github.com/pranavkumaarofficial/nlcli-wizard",
  },
  {
    name: "oauth-for-dummies",
    desc: "Add GitHub/Google OAuth to a FastAPI app in a single command.",
    lang: "Python",
    tags: ["OAuth2", "FastAPI", "CLI"],
    repo: "https://github.com/pranavkumaarofficial/oauth-for-dummies",
  },
  {
    name: "python-est",
    desc: "Enterprise EST (RFC 7030) certificate-enrollment server: multi-CA, TLS 1.3, production-ready PKI.",
    lang: "Python",
    tags: ["PKI", "TLS 1.3", "Security"],
    repo: "https://github.com/pranavkumaarofficial/python-est",
  },
  {
    name: "otpilot",
    desc: "Self-hosted, zero-knowledge OTP sharing: an AES-256-GCM encrypted relay with QR onboarding, Tailscale-ready.",
    lang: "Kotlin · Node.js",
    tags: ["Encryption", "Privacy", "PWA"],
    repo: "https://github.com/pranavkumaarofficial/otpilot",
  },
  {
    name: "ping-claude",
    desc: "Drive your local Claude Code from your phone: approve permissions and send commands over Tailscale, nothing leaves your machine.",
    lang: "Python",
    tags: ["Claude Code", "Tailscale", "Remote"],
    repo: "https://github.com/pranavkumaarofficial/ping-claude",
  },
  {
    name: "keeper",
    desc: "A Claude Code safety hook that blocks dangerous shell commands, rendering a goalkeeper in ASCII art to reject them.",
    lang: "Python",
    tags: ["AI Safety", "Claude Code", "CLI"],
    repo: "https://github.com/pranavkumaarofficial/keeper",
  },
  {
    name: "venvy",
    desc: "Fast, cross-platform Python virtual-environment manager.",
    lang: "Python",
    tags: ["Dev Tools", "CLI"],
    repo: "https://github.com/pranavkumaarofficial/venvy",
  },
];

const EXPERIENCE = [
  {
    when: "2024 – 2026",
    title: "Software Engineer I",
    where: "Enterprise healthcare technology · Bangalore",
    desc: "Enterprise interoperability and cybersecurity. Built production PKI/EST certificate infrastructure. Company details on LinkedIn.",
    link: "projects/est-service.html",
  },
  {
    when: "2022 – 2024",
    title: "Applied AI Developer",
    where: "PESU Venture Labs · Bangalore",
    desc: "Shipped applied AI/ML for external clients: computer vision, semantic search, generative AI.",
  },
];

const EDUCATION = [
  {
    when: "2026 – 2028",
    title: "MS, Computer Science",
    where: "University of Massachusetts Amherst",
    desc: "Incoming Fall 2026.",
  },
  {
    when: "2026",
    title: "Research publication · ICMLC 2026",
    where: "Accepted for presentation, Feb 2026",
    desc: "When Graph Structure Hurts: Lightweight Path Ranking for Dense KG-RAG.",
    link: "projects/kg-rag-research.html",
  },
];

const WRITING = [
  // Add Medium articles here:
  // { when: "Jun 2026", title: "Article title", where: "Medium", link: "https://medium.com/@you/..." },
];

const SKILLS = [
  { label: "Languages", items: "Python, TypeScript, SQL, Bash" },
  { label: "ML / LLM", items: "PyTorch, LangGraph, RAG, embeddings, BM25, GNNs, OpenAI Agents SDK" },
  { label: "Infrastructure", items: "Docker, Kubernetes, Apache Iceberg, PKI/EST, CI/CD" },
  { label: "Focus areas", items: "LLM orchestration, retrieval systems, production ML infrastructure" },
];
